import { GIOITHIEU } from './gioithieu';

export const ds_gioithieu: GIOITHIEU[] = [
    {
        "magioithieu": "GT001", "tieude": "Về chúng tôi",
        "noidung": "<div> Sàn giao dịch bất động sản Đất Xanh ra đời đã hiện thực hóa chuỗi giá trị dịch vụ khách hàng và giải pháp bán hàng.Cùng với đội ngũ nhân viên chuyên nghiệp, tận tâm, giàu kinh nghiệm đã góp một phần quan trọng vào việc hoàn thành sứ mệnh của Công ty, nâng khả năng cung cấp sản phẩm, dịch vụ của Đất Xanh lên một tầm cao mới. </div> <div> </div> <div> <h3> Tất cả các giải pháp mà Đất Xanh cung cấp đều được phân tích một cách chuyên sâu, hướng đến phục vụ và giải quyết những vướng mắc một cách nhanh chóng và thỏa mãn tối đa nhu cầu của khách hàng. </h3> Chúng tôi  không chỉ cung cấp sản phẩm bất động sản đơn thuần mà còn mang đến cho khách hàng sự an tâm, tin tưởng và tự hào khi sở hữu sản phẩm của Đất Xanh. </div>",
        "icon": "fa fa-newspaper-o"
    },
    {
        "magioithieu": "GT002", "tieude": "Lĩnh vực hoạt động",
        "noidung": "Sàn giao dịch bất động sản Đất Xanh ra đời đã hiện thực hóa chuỗi giá trị dịch vụ khách hàng và giải pháp bán hàng. Cùng với đội ngũ nhân viên chuyên nghiệp, tận tâm, giàu kinh nghiệm đã góp một phần quan trọng vào việc hoàn thành sứ mệnh của Công ty, nâng khả năng cung cấp sản phẩm, dịch vụ của Đất Xanh lên một tầm cao mới.Tất cả các giải pháp mà Đất Xanh cung cấp đều được phân tích một cách chuyên sâu, hướng đến phục vụ và giải quyết những vướng mắc một cách nhanh chóng và thỏa mãn tối đa nhu cầu của khách hàng. Chúng tôi không chỉ cung cấp sản phẩm bất động sản đơn thuần mà còn mang đến cho khách hàng sự an tâm, tin tưởng và tự hào khi sở hữu sản phẩm của Đất Xanh.Dịch vụ của Đất Xanh bao gồm:Môi giới và tư vấn bất động sản: Dịch vụ môi giới và tư vấn bất động sản của Đất Xanh luôn làm gia tăng cơ hội giao dịch. Luôn thấu hiểu nhu cầu, lựa chọn của khách hàng, chúng tôi có kế hoạch và giải pháp bán hàng hiệu quả cũng như tư vấn các giải pháp về thị trường và giá cho chủ đầu tư dự án và khách hàng.Quản lý bất động sản và cho thuê căn hộ: Sàn giao dịch bất động sản Đất Xanh có đội ngũ chuyên viên tư vấn tận tâm, giàu kinh nghiệm sẽ giúp quý khách quản lý và giao dịch bất động sản phù hợp với nhu cầu và làm gia tăng giá trị các bất động sản của khách hàng.Với đội ngũ nhân viên chuyên nghiệp, tận tâm, giàu kinh nghiệm sẽ đảm bảo mang đến cho khách hàng sự an tâm, hài lòng khi đến với Đất Xanh.HỆ THỐNG SÀN GIAO DỊCH (xem chi tiết tại đây)HỆ THỐNG ĐẠI LÝ, ĐỐI TÁCVới số lượng hơn 200 đại lý và đối tác rộng khắp đã góp phần phân phối hàng ngàn sản phẩm đến với khách hàng trong cả nước hàng năm. Đặc biệt, với việc sáng lập liên minh G5 - Liên minh bất động sản mạnh nhất Việt Nam - Đất Xanh đã phủ khắp cả nước và trở thành Tập đoàn phân phối bất động sản lớn nhất nước.HỆ THỐNG CỘNG TÁC VIÊNVới số lượng hơn 2.000 Cộng tác viên là các chuyên gia tư vấn bất động sản chuyên nghiệp từ trang thương mại điện tử bất động sản (www.123muanha.vn), Đất Xanh tiếp tục tiên phong ứng dụng công nghệ mới trong hoạt động kinh doanh để sẵn sàng hội nhập Quốc tế và góp phần củng cố sức mạnh về lĩnh vực phân phối của Đất Xanh.",
        "icon": "fa fa-newspaper-o"
    },
]