import { GIOITHIEU } from './gioithieu';

export const ds_gioithieu: GIOITHIEU[] = [
    {
        "magioithieu": 1, "tieude": "Về chúng tôi",
        "noidung": "Tháng 11/2003 thương hiệu Ðất Xanh chính thức có mặt trên thị truờng bất động sản Việt Nam. Trải qua một thập kỷ hình thành và phát triển, Ðất Xanh luôn vững vàng với mục tiêu mang lại cho khách hàng những sản phẩm bất động sản tốt nhất bằng dịch vụ chuyên nghiệp nhất.Với tiềm lực mạnh về tài chính, vững vàng về kinh nghiệm, cùng đội ngũ cán bộ nhân viên được đào tạo chuyên nghiệp, nhiệt tình, năng động, sáng tạo và làm việc hiệu quả, Ðất Xanh nỗ lực không ngừng trong mọi hoàn cảnh để khẳng định và nâng cao vị thế của mình trên thị trường bất động sản Việt Nam, giữ vững niềm tin trong tâm trí khách hàng và đối tác.Tự tin với sức mạnh của ba mũi nhọn là Ðầu tư – Xây dựng – Dịch vụ, Ðất Xanh đã và đang khẳng định vị thế là Nhà cung cấp giải pháp bất động sản toàn diện nhằm tạo lập cuộc sống ưu việt cho khách hàng.Với  chiến lược đa ngành nghề, đa sở hữu và đa quốc gia, Đất Xanh chủ trương liên doanh, liên kết, hợp tác với các tổ chức Tài chính, Ngân hàng, Công nghệ, Nhân lực...nhằm tối ưu hóa lợi thế cạnh tranh trên thị trường.Đất Xanh là một trong những doanh nghiệp có được nét văn hóa riêng, tạo được môi trường lý tưởng cho mọi người phát triển sự nghiệp trong lĩnh vực bất động sản, đồng thời đề cao mục tiêu phát triển doanh nghiệp gắn với sự phát triển xã hội, luôn có những hành động thiết thực chung tay vì một cộng đồng bền vững và nhân ái.Với thế và lực sẵn có cùng sự quyết tâm không ngừng, chúng tôi tin rằng Đất Xanh có đủ cơ sở để đạt được những mục tiêu chiến lược đã đề ra. Đất Xanh sẽ trở thành một trong những tập đoàn kinh tế hàng đầu Việt Nam và vươn ra thế giới trong một tương lai gần nhất.",
        "icon": ""
    },
    {
        "magioithieu": 2, "tieude": "Lĩnh vực hoạt động",
        "noidung": "Sàn giao dịch bất động sản Đất Xanh ra đời đã hiện thực hóa chuỗi giá trị dịch vụ khách hàng và giải pháp bán hàng. Cùng với đội ngũ nhân viên chuyên nghiệp, tận tâm, giàu kinh nghiệm đã góp một phần quan trọng vào việc hoàn thành sứ mệnh của Công ty, nâng khả năng cung cấp sản phẩm, dịch vụ của Đất Xanh lên một tầm cao mới.Tất cả các giải pháp mà Đất Xanh cung cấp đều được phân tích một cách chuyên sâu, hướng đến phục vụ và giải quyết những vướng mắc một cách nhanh chóng và thỏa mãn tối đa nhu cầu của khách hàng. Chúng tôi không chỉ cung cấp sản phẩm bất động sản đơn thuần mà còn mang đến cho khách hàng sự an tâm, tin tưởng và tự hào khi sở hữu sản phẩm của Đất Xanh.Dịch vụ của Đất Xanh bao gồm:Môi giới và tư vấn bất động sản: Dịch vụ môi giới và tư vấn bất động sản của Đất Xanh luôn làm gia tăng cơ hội giao dịch. Luôn thấu hiểu nhu cầu, lựa chọn của khách hàng, chúng tôi có kế hoạch và giải pháp bán hàng hiệu quả cũng như tư vấn các giải pháp về thị trường và giá cho chủ đầu tư dự án và khách hàng.Quản lý bất động sản và cho thuê căn hộ: Sàn giao dịch bất động sản Đất Xanh có đội ngũ chuyên viên tư vấn tận tâm, giàu kinh nghiệm sẽ giúp quý khách quản lý và giao dịch bất động sản phù hợp với nhu cầu và làm gia tăng giá trị các bất động sản của khách hàng.Với đội ngũ nhân viên chuyên nghiệp, tận tâm, giàu kinh nghiệm sẽ đảm bảo mang đến cho khách hàng sự an tâm, hài lòng khi đến với Đất Xanh.HỆ THỐNG SÀN GIAO DỊCH (xem chi tiết tại đây)HỆ THỐNG ĐẠI LÝ, ĐỐI TÁCVới số lượng hơn 200 đại lý và đối tác rộng khắp đã góp phần phân phối hàng ngàn sản phẩm đến với khách hàng trong cả nước hàng năm. Đặc biệt, với việc sáng lập liên minh G5 - Liên minh bất động sản mạnh nhất Việt Nam - Đất Xanh đã phủ khắp cả nước và trở thành Tập đoàn phân phối bất động sản lớn nhất nước.HỆ THỐNG CỘNG TÁC VIÊNVới số lượng hơn 2.000 Cộng tác viên là các chuyên gia tư vấn bất động sản chuyên nghiệp từ trang thương mại điện tử bất động sản (www.123muanha.vn), Đất Xanh tiếp tục tiên phong ứng dụng công nghệ mới trong hoạt động kinh doanh để sẵn sàng hội nhập Quốc tế và góp phần củng cố sức mạnh về lĩnh vực phân phối của Đất Xanh.",
        "icon": ""
    },
]